export const ADD_FAVOURITE_SUCCESS = "ADD_FAVOURITE_SUCCESS";
export const ADD_FAVOURITE_FAILED = "ADD_FAVOURITE_FAILED";

export const FETCH_FAVOURITE_LOADING = "FETCH_FAVOURITE_LOADING";
export const FETCH_FAVOURITE_SUCCESS = "FETCH_FAVOURITE_SUCCESS";
export const FETCH_FAVOURITE_FAILED = "FETCH_FAVOURITE_FAILED";

export const DELETE_FAVOURITE_SUCCESS = "DELETE_FAVOURITE_SUCCESS";
export const DELETE_FAVOURITE_FAILED = "DELETE_FAVOURITE_FAILED";